import { Header } from '@/components/Layout/Header'
import './globals.scss'
import '@/styles/_ui.scss'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Footer } from '@/components/Layout/Footer'
import { Providers } from '@/redux/provider'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <Header />
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
